name: Rust

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
  
    env:
      CARGO_INCREMENTAL: 0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Install FoundationDB
      uses: ./.github/actions/foundationdb

    - name: Install Clang
      if: matrix.os == 'windows-latest'
      run: |
        curl -fsSL -o LLVM9.exe https://releases.llvm.org/9.0.0/LLVM-9.0.0-win64.exe
        7z x LLVM9.exe -y -o"C:/Program Files/LLVM"

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Build
      run: cargo --color always build --verbose 

    - name: Run tests
      run: |
        cargo --color always test --manifest-path foundationdb-sys/Cargo.toml
        cargo --color always test --manifest-path foundationdb-gen/Cargo.toml
        cargo --color always test --manifest-path foundationdb/Cargo.toml
        cargo --color always test --manifest-path foundationdb/Cargo.toml --no-default-features --features fdb-6_0 --tests
        cargo --color always test --manifest-path foundationdb-bench/Cargo.toml
        cargo --color always run --manifest-path foundationdb/Cargo.toml --example class-scheduling
